#spring:
#  application:
#    name: zzuoj-user
#spring:
#  cloud:
#    config:
#      uri: http://localhost:7011
#      label: master
#      profile: dev
#      name: config-zzuoj-user

spring:
  profiles:
    active: test
---
server:
  port: 8202
spring:
  profiles: dev
  application:
    name: zzuoj-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: yY139411.
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 6000

eureka:
  instance:
    instance-id: zzuoj-user-8202  #修改Eureka上的默认描述信息
  client:
    service-url:
      defualtZone: http://eureka01:7001/eureka
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: zzuoj-user
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/demo??useUnicode=true&characterEncoding=UTF-8
    username: root
    password: yY139411.
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 6000
eureka:
  instance:
    instance-id: zzuoj-user-8202  #修改Eureka上的默认描述信息
  client:
    service-url:
      defualtZone: http://eureka01:7001/eureka