spring:
  profiles:
    active: test

---
zzuoj:
  filter:
    allowPaths: "/zzuoj-problem/problem/show,/zzuoj-problem/problem/cnt,/zzuoj-problem/problem/get,
                 /zzuoj-file/news/show,/zzuoj-file/news/cnt,/zzuoj-file/news/get,
                 /zzuoj-user/user/login,/zzuoj-user/user/registry,
                 /zzuoj-contest/contest/show,/zzuoj-contest/contest/cnt,/zzuoj-contest/contest/get"

server:
  port: 9001
spring:
  profiles: dev
  application:
    name: zzuoj-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      discovery:
        locator:
          enabled: true # 开启 Gateway 服务注册中心服务发现
          lower-case-service-id: true #使用小写
      globalcors:
        corsConfigurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
#      下面的配置方法需要配置很多微服务，使用动态路由配置之服务名称转发，也就是上面的配置。http://ip:gateway_port/servername/正常请求的链接
#      routes:
#        - id: zzuoj-auth
#          uri: lb://ZZUOJ-AUTH #lb是load balance # 动态路由
#          uri: http://localhost:8201/ #静态路由
#          predicates:
#            - Path=/auth/**
#            - Query=token #必须有?token=*** 参数
#            - Query=token, abc. # 正则匹配 ?token=abcd
#            - Method=Get # 匹配Get请求

# Eureka Server 配置
eureka:
  instance:
    instance-id: zzuoj-gateway-9001
  client:
    service-url:
      defaultZone: http://eureka01:7001/eureka

ribbon:
  ReadTimeout=60000
  ConnectTimeout=60000
  MaxAutoRetries=0
  MaxAutoRetriesNextServer=1

---
zzuoj:
  filter:
    allowPaths: "/zzuoj-problem/problem/show,/zzuoj-problem/problem/cnt,/zzuoj-problem/problem/get,
                 /zzuoj-file/news/show,/zzuoj-file/news/cnt,/zzuoj-file/news/get,
                 /zzuoj-user/user/login,/zzuoj-user/user/registry,
                 /zzuoj-contest/contest/show,/zzuoj-contest/contest/cnt,/zzuoj-contest/contest/get"

server:
  port: 9001
spring:
  profiles: test
  application:
    name: zzuoj-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      discovery:
        locator:
          enabled: true # 开启 Gateway 服务注册中心服务发现
          lower-case-service-id: true #使用小写
      globalcors:
        corsConfigurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
#      下面的配置方法需要配置很多微服务，使用动态路由配置之服务名称转发，也就是上面的配置。http://ip:gateway_port/servername/正常请求的链接
#      routes:
#        - id: zzuoj-auth
#          uri: lb://ZZUOJ-AUTH #lb是load balance # 动态路由
#          uri: http://localhost:8201/ #静态路由
#          predicates:
#            - Path=/auth/**
#            - Query=token #必须有?token=*** 参数
#            - Query=token, abc. # 正则匹配 ?token=abcd
#            - Method=Get # 匹配Get请求

# Eureka Server 配置
eureka:
  instance:
    instance-id: zzuoj-gateway-9001
  client:
    service-url:
      defaultZone: http://eureka01:7001/eureka


ribbon:
  ReadTimeout=60000
  ConnectTimeout=60000
  MaxAutoRetries=0
  MaxAutoRetriesNextServer=1
