spring:
  application:
    name: zzuoj-conf-client-test-8201

# 用户级别的配置
#server:
#  port: 3302
#management:
#  endpoint:
#    shutdown:
#      enabled: false
#  endpoints:
#    web:
#      exposure:
#        include: "*"
##  management 是关于 actuator 相关的，接下来自动刷新配置的时候需要使用。
#
#data:
#  env: NaN
#  user:
#    username: NaN
#    password: NaN
# data是无法读取配置中心的配置时，使用此配置，以免服务无法启动。